apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: the-image=gcr.io/my-gcp-learning-dev/docker-getting-started:0.1
    argocd-image-updater.argoproj.io/the-image.update-strategy: digest
  name: kustomize-getting-started
  namespace: argocd
spec:
  destination:
    namespace: default 
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/dwi-mfbcs/argocd-example-apps.git'
    path: helm-getting-started
    targetRevision: HEAD
  project: default
  syncPolicy: {}
