apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/my-gcp-learning-dev/ks-guestbook-demo:~0.3
  name: kustomize-guestbook-2
  namespace: argocd
spec:
  destination:
    namespace: default 
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/dwi-mfbcs/argocd-example-apps.git'
    path: helm-guestbook
    targetRevision: HEAD
  project: default
  syncPolicy: {}
